name: employee_id_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # دعم اللغات والتقويم العربي
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0

  # الواجهات والأيقونات
  flutter_svg: ^2.0.10

  # إدارة البيانات
  provider: ^6.1.2

  # التخزين المحلي
  shared_preferences: ^2.2.2

  # استيراد وإنشاء ملفات Excel واختيار الملفات
  file_picker: ^9.1.0
  excel: ^4.0.0
  path_provider: ^2.1.0

  # تنزيل الملفات مباشرة على Web/Chrome
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
