// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGO_zigenVFx4-Ja7HpNlIym7gn7uVvR4',
    appId: '1:158172020221:web:a4bb4a8bd83824c97fad94',
    messagingSenderId: '158172020221',
    projectId: 'employees-2eed6',
    authDomain: 'employees-2eed6.firebaseapp.com',
    storageBucket: 'employees-2eed6.firebasestorage.app',
    measurementId: 'G-XNSJSF7DDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EomkGHorghPEHTKFGaWxCtLgOKDgSDY',
    appId: '1:158172020221:android:cafd9ee498eb65087fad94',
    messagingSenderId: '158172020221',
    projectId: 'employees-2eed6',
    storageBucket: 'employees-2eed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oRmm7MoUcKSFWrcV2A5N9jU_sXePBKE',
    appId: '1:158172020221:ios:fc9effefc7628e747fad94',
    messagingSenderId: '158172020221',
    projectId: 'employees-2eed6',
    storageBucket: 'employees-2eed6.firebasestorage.app',
    iosBundleId: 'com.employee.identity.employeeIdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6oRmm7MoUcKSFWrcV2A5N9jU_sXePBKE',
    appId: '1:158172020221:ios:fc9effefc7628e747fad94',
    messagingSenderId: '158172020221',
    projectId: 'employees-2eed6',
    storageBucket: 'employees-2eed6.firebasestorage.app',
    iosBundleId: 'com.employee.identity.employeeIdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGO_zigenVFx4-Ja7HpNlIym7gn7uVvR4',
    appId: '1:158172020221:web:e8895d4530e621c27fad94',
    messagingSenderId: '158172020221',
    projectId: 'employees-2eed6',
    authDomain: 'employees-2eed6.firebaseapp.com',
    storageBucket: 'employees-2eed6.firebasestorage.app',
    measurementId: 'G-M3QXT05LHN',
  );
}
